FROM python:3.10-slim

# Устанавливаем системные зависимости для базы данных
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

WORKDIR /code

# Устанавливаем зависимости Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем проект
COPY . .

# Настройка entrypoint
COPY ./entrypoint.sh /code/entrypoint.sh
RUN chmod +x /code/entrypoint.sh

# На Render лучше использовать полный путь
ENTRYPOINT ["/code/entrypoint.sh"]